app = "zira-suite"
primary_region = "iad"

[build]

[env]
  PORT = "3000"
  MANAGER_PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[checks]
  [checks.health]
    type = "http"
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    port = 3000
    timeout = "10s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"