name: Deploy Zira Suite to Fly.io

on:
  push:
    branches: [main, master]
    paths: 
      - 'ManagerServer-linux-x64/**'
      - '.github/workflows/deploy-flyio.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        working-directory: ManagerServer-linux-x64
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
      - name: Test deployment
        run: |
          sleep 30
          curl -f https://zira-suite.fly.dev/health || exit 1
        continue-on-error: true